apiVersion: v1
kind: Service
metadata:
  name: mybookstoreservice
  namespace: default
spec:
  selector:
    app: bookstore
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8001
  type: NodePort
  